-- 0014_seed_roles_capabilities.sql
-- Core platform. Seeds the role catalogue, the capability catalogue and the role x capability
-- matrix published in docs/12_ROLES_AND_PERMISSIONS.md. Idempotent.
-- A capability named by a route guard but absent here is a deployment error: the guard must fail
-- loudly at boot rather than deny everyone silently.

INSERT INTO roles (code, name, module, description, position) VALUES
 ('platform_admin',     'Platform administrator','platform','Accounts, roles, settings, config, audit. Produces no training evidence.',10),
 ('training_manager',   'Training manager',      'training','Owns the training programme: templates, library, programme analytics, whole population.',20),
 ('assessment_manager', 'Assessment manager',    'training','Owns assessment quality: assessor analytics, calibration, record amendment.',30),
 ('examiner',           'Examiner',              'training','Conducts and signs checks.',40),
 ('instructor',         'Instructor',            'training','Conducts and grades training sessions.',50),
 ('ground_instructor',  'Ground instructor',     'training','As instructor, restricted to ground and classroom template kinds.',60),
 ('qms_admin',          'QMS administrator',     'qms',     'Qualification types and records, certificate issue, approval queue.',70),
 ('compliance_verifier','Compliance verifier',   'qms',     'Read-only across compliance evidence, plus attestation signing.',80),
 ('planner',            'Planner',               'planning','Builds and publishes schedules; reads validity, never grades.',90),
 ('records_officer',    'Records officer',       'dms',     'Custody of documents and records: import, filing, retention, export.',100),
 ('trainee',            'Trainee',               'training','Reads their own records, analysis and qualifications.',110)
ON CONFLICT (code) DO NOTHING;

INSERT INTO capabilities (code, module, resource, action, is_scoped, is_overridable, description) VALUES
 ('platform.users.view','platform','users','view',false,true,'List and read user accounts'),
 ('platform.users.create','platform','users','create',false,true,'Create an account'),
 ('platform.users.manage','platform','users','manage',false,true,'Edit, deactivate, soft-delete an account'),
 ('platform.roles.assign','platform','roles','assign',false,true,'Grant and revoke role grants'),
 ('platform.audit.view','platform','audit','view',false,true,'Read the audit log'),
 ('platform.settings.manage','platform','settings','manage',false,true,'Edit operational settings'),
 ('platform.config.manage','platform','config','manage',false,true,'Load and activate a config version'),
 ('platform.tickets.triage','platform','tickets','triage',false,true,'Support ticket queue'),
 ('people.view','platform','people','view',true,true,'Read a roster row'),
 ('people.manage','platform','people','manage',false,true,'Edit roster attributes, watch list, concern override'),
 ('training.templates.view','training','templates','view',false,true,'Read templates and elements'),
 ('training.templates.configure','training','templates','configure',false,true,'Author a draft template version'),
 ('training.templates.publish','training','templates','publish',false,true,'Publish or retire a template version'),
 ('training.library.manage','training','library','manage',false,true,'Edit the element library'),
 ('training.sessions.view','training','sessions','view',true,true,'Read a session and its grades'),
 ('training.sessions.create','training','sessions','create',false,true,'Open a session'),
 ('training.sessions.grade','training','sessions','grade',true,true,'Write element and competency grades'),
 ('training.sessions.sign','training','sessions','sign',true,true,'Apply an assessor signature'),
 ('training.sessions.finalize','training','sessions','finalize',true,true,'Freeze a session into records'),
 ('training.sessions.unsign','training','sessions','unsign',false,true,'Reverse a signature'),
 ('training.sessions.delete','training','sessions','delete',false,true,'Soft-delete a session'),
 ('training.records.view','training','records','view',true,true,'Read a frozen record'),
 ('training.records.import','training','records','import',false,true,'Ingest external records'),
 ('training.records.amend','training','records','amend',false,true,'Set an outcome override or correct metadata'),
 ('training.records.delete','training','records','delete',false,true,'Soft-delete a record'),
 ('training.analysis.view','training','analysis','view',true,true,'Read an analysis run'),
 ('training.analysis.run','training','analysis','run',true,true,'Request an analysis run'),
 ('training.analytics.programme.view','training','analytics_programme','view',false,true,'Programme and cohort analytics'),
 ('training.analytics.assessor.view','training','analytics_assessor','view',true,true,'Assessor grading analytics; excludes the holder'),
 ('training.certificates.view','training','certificates','view',false,false,'View a completion certificate'),
 ('training.certificates.issue','training','certificates','issue',false,false,'Issue a completion certificate'),
 ('qms.qualtypes.configure','qms','qual_types','configure',false,true,'Qualification type catalogue'),
 ('qms.qualifications.view','qms','qualifications','view',true,true,'Read qualification validity'),
 ('qms.qualifications.manage','qms','qualifications','manage',false,true,'Create, supersede, override a qualification'),
 ('qms.approvals.decide','qms','approvals','decide',false,true,'Approve or reject a submitted document'),
 ('qms.attestations.sign','qms','attestations','sign',false,false,'Sign a compliance attestation'),
 ('qms.events.view','qms','events','view',false,true,'Read the QMS event timeline'),
 ('dms.documents.view','dms','documents','view',true,true,'Read a stored document'),
 ('dms.documents.upload','dms','documents','upload',true,true,'Upload into a subject folder'),
 ('dms.documents.manage','dms','documents','manage',false,true,'File, supersede, soft-delete documents'),
 ('dms.retention.configure','dms','retention','configure',false,true,'Edit retention rules'),
 ('planning.schedule.view','planning','schedule','view',true,true,'Read a schedule'),
 ('planning.schedule.edit','planning','schedule','edit',false,true,'Draft a schedule'),
 ('planning.schedule.publish','planning','schedule','publish',false,true,'Publish a schedule'),
 ('data.export','platform','export','run',true,true,'Export rows the caller can already see'),
 ('data.bulk_export','platform','export','bulk',false,true,'Whole-population export and reprocessing'),
 ('integration.api_keys.manage','integration','api_keys','manage',false,true,'Issue and revoke external API keys')
ON CONFLICT (code) DO NOTHING;

-- The role x capability matrix. Scopes: own | assigned | team | org | all.
-- platform_admin deliberately holds no grading, signing, finalising, amending or issuing
-- capability: it administers the system and does not produce training evidence.
INSERT INTO role_capabilities (role_code, capability_code, scope) VALUES
 ('platform_admin','platform.users.view','all'),
 ('platform_admin','platform.users.create','all'),
 ('platform_admin','platform.users.manage','all'),
 ('platform_admin','platform.roles.assign','all'),
 ('platform_admin','platform.audit.view','all'),
 ('platform_admin','platform.settings.manage','all'),
 ('platform_admin','platform.config.manage','all'),
 ('platform_admin','platform.tickets.triage','all'),
 ('platform_admin','people.view','all'),
 ('platform_admin','people.manage','all'),
 ('platform_admin','dms.retention.configure','all'),
 ('platform_admin','integration.api_keys.manage','all'),

 ('training_manager','platform.users.view','all'),
 ('training_manager','platform.users.create','all'),
 ('training_manager','people.view','all'),
 ('training_manager','people.manage','all'),
 ('training_manager','training.templates.view','all'),
 ('training_manager','training.templates.configure','all'),
 ('training_manager','training.templates.publish','all'),
 ('training_manager','training.library.manage','all'),
 ('training_manager','training.sessions.view','all'),
 ('training_manager','training.sessions.create','all'),
 ('training_manager','training.sessions.finalize','all'),
 ('training_manager','training.sessions.unsign','all'),
 ('training_manager','training.sessions.delete','all'),
 ('training_manager','training.records.view','all'),
 ('training_manager','training.records.import','all'),
 ('training_manager','training.records.delete','all'),
 ('training_manager','training.analysis.view','all'),
 ('training_manager','training.analysis.run','all'),
 ('training_manager','training.analytics.programme.view','all'),
 ('training_manager','training.analytics.assessor.view','all'),
 ('training_manager','qms.qualifications.view','all'),
 ('training_manager','dms.documents.view','all'),
 ('training_manager','dms.documents.upload','all'),
 ('training_manager','planning.schedule.view','all'),
 ('training_manager','data.export','all'),
 ('training_manager','data.bulk_export','all'),

 ('assessment_manager','people.view','all'),
 ('assessment_manager','training.templates.view','all'),
 ('assessment_manager','training.sessions.view','all'),
 ('assessment_manager','training.sessions.create','all'),
 ('assessment_manager','training.sessions.finalize','all'),
 ('assessment_manager','training.sessions.unsign','all'),
 ('assessment_manager','training.records.view','all'),
 ('assessment_manager','training.records.amend','all'),
 ('assessment_manager','training.analysis.view','all'),
 ('assessment_manager','training.analysis.run','all'),
 ('assessment_manager','training.analytics.programme.view','all'),
 ('assessment_manager','training.analytics.assessor.view','all'),
 ('assessment_manager','dms.documents.view','all'),
 ('assessment_manager','data.export','all'),

 ('examiner','people.view','assigned'),
 ('examiner','training.templates.view','all'),
 ('examiner','training.sessions.view','assigned'),
 ('examiner','training.sessions.create','all'),
 ('examiner','training.sessions.grade','assigned'),
 ('examiner','training.sessions.sign','assigned'),
 ('examiner','training.sessions.finalize','assigned'),
 ('examiner','training.records.view','assigned'),
 ('examiner','training.analysis.view','assigned'),
 ('examiner','training.analysis.run','assigned'),
 ('examiner','qms.qualifications.view','assigned'),
 ('examiner','dms.documents.view','assigned'),
 ('examiner','dms.documents.upload','assigned'),
 ('examiner','planning.schedule.view','own'),
 ('examiner','data.export','assigned'),

 ('instructor','people.view','assigned'),
 ('instructor','training.templates.view','all'),
 ('instructor','training.sessions.view','assigned'),
 ('instructor','training.sessions.create','all'),
 ('instructor','training.sessions.grade','assigned'),
 ('instructor','training.sessions.sign','assigned'),
 ('instructor','training.sessions.finalize','assigned'),
 ('instructor','training.records.view','assigned'),
 ('instructor','training.analysis.view','assigned'),
 ('instructor','training.analysis.run','assigned'),
 ('instructor','dms.documents.view','assigned'),
 ('instructor','dms.documents.upload','assigned'),
 ('instructor','planning.schedule.view','own'),
 ('instructor','data.export','assigned'),

 -- ground_instructor differs from instructor by TEMPLATE KIND, which is a row-level restriction
 -- enforced in the read ACL, not a capability. Its only catalogue difference is analysis.run.
 ('ground_instructor','people.view','assigned'),
 ('ground_instructor','training.templates.view','all'),
 ('ground_instructor','training.sessions.view','assigned'),
 ('ground_instructor','training.sessions.create','all'),
 ('ground_instructor','training.sessions.grade','assigned'),
 ('ground_instructor','training.sessions.sign','assigned'),
 ('ground_instructor','training.sessions.finalize','assigned'),
 ('ground_instructor','training.records.view','assigned'),
 ('ground_instructor','training.analysis.view','assigned'),
 ('ground_instructor','dms.documents.view','assigned'),
 ('ground_instructor','dms.documents.upload','assigned'),
 ('ground_instructor','planning.schedule.view','own'),
 ('ground_instructor','data.export','assigned'),

 ('qms_admin','people.view','all'),
 ('qms_admin','training.records.view','all'),
 ('qms_admin','training.certificates.view','all'),
 ('qms_admin','training.certificates.issue','all'),
 ('qms_admin','qms.qualtypes.configure','all'),
 ('qms_admin','qms.qualifications.view','all'),
 ('qms_admin','qms.qualifications.manage','all'),
 ('qms_admin','qms.approvals.decide','all'),
 ('qms_admin','qms.events.view','all'),
 ('qms_admin','dms.documents.view','all'),
 ('qms_admin','dms.documents.upload','all'),
 ('qms_admin','dms.documents.manage','all'),
 ('qms_admin','dms.retention.configure','all'),
 ('qms_admin','data.export','all'),

 -- compliance_verifier is read-plus-attest: it changes nothing that it verifies.
 ('compliance_verifier','platform.audit.view','all'),
 ('compliance_verifier','people.view','all'),
 ('compliance_verifier','training.templates.view','all'),
 ('compliance_verifier','training.sessions.view','all'),
 ('compliance_verifier','training.records.view','all'),
 ('compliance_verifier','training.analytics.programme.view','all'),
 ('compliance_verifier','training.certificates.view','all'),
 ('compliance_verifier','qms.qualifications.view','all'),
 ('compliance_verifier','qms.attestations.sign','all'),
 ('compliance_verifier','qms.events.view','all'),
 ('compliance_verifier','dms.documents.view','all'),
 ('compliance_verifier','data.export','all'),

 -- planner reads validity to plan against it, and sees no grades at any scope.
 ('planner','people.view','org'),
 ('planner','qms.qualifications.view','org'),
 ('planner','planning.schedule.view','all'),
 ('planner','planning.schedule.edit','all'),
 ('planner','planning.schedule.publish','all'),

 ('records_officer','people.view','all'),
 ('records_officer','training.sessions.view','all'),
 ('records_officer','training.records.view','all'),
 ('records_officer','training.records.import','all'),
 ('records_officer','qms.qualifications.view','all'),
 ('records_officer','dms.documents.view','all'),
 ('records_officer','dms.documents.upload','all'),
 ('records_officer','dms.documents.manage','all'),
 ('records_officer','data.export','all'),
 ('records_officer','data.bulk_export','all'),

 -- trainee holds nothing above 'own', at any scope, ever.
 ('trainee','people.view','own'),
 ('trainee','training.sessions.view','own'),
 ('trainee','training.records.view','own'),
 ('trainee','training.analysis.view','own'),
 ('trainee','qms.qualifications.view','own'),
 ('trainee','dms.documents.view','own'),
 ('trainee','dms.documents.upload','own'),
 ('trainee','planning.schedule.view','own'),
 ('trainee','data.export','own')
ON CONFLICT (role_code, capability_code, scope) DO NOTHING;

DO $$
DECLARE n_roles INT; n_caps INT; n_grants INT;
BEGIN
  SELECT count(*) INTO n_roles  FROM roles;
  SELECT count(*) INTO n_caps   FROM capabilities;
  SELECT count(*) INTO n_grants FROM role_capabilities;
  RAISE NOTICE 'permission model seeded: % roles, % capabilities, % grants', n_roles, n_caps, n_grants;
  IF n_roles < 11 OR n_caps < 47 THEN
    RAISE EXCEPTION 'permission seed incomplete: % roles, % capabilities', n_roles, n_caps;
  END IF;
END $$;
